# Generated by Django 5.0.7 on 2024-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('mfg_year', models.DateField()),
                ('car_img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('color', models.CharField(max_length=15)),
                ('no_of_seets', models.IntegerField(max_length=2)),
                ('engine_type', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
    ]
